;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="State.Player.Crouching",NewTagName="State.Player.IsCrouching")
+GameplayTagRedirects=(OldTagName="State.Player.IsInAir",NewTagName="State.Player.IsJumping")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Player.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Crouch",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Death",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Interact",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Prone",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Reload",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Roll",DevComment="")
+GameplayTagList=(Tag="Ability.Player.SpecialAbility",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Zoom",DevComment="")
+GameplayTagList=(Tag="Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Crouch",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Death",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Prone",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Reload",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Roll",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Sprint",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Damaged",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Footstep",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.SA_Active",DevComment="")
+GameplayTagList=(Tag="Monster.Region.Body",DevComment="")
+GameplayTagList=(Tag="Monster.Region.Head",DevComment="")
+GameplayTagList=(Tag="Monster.Type.Boss",DevComment="보스 몬스터")
+GameplayTagList=(Tag="Monster.Type.Elite",DevComment="엘리트 몬스터")
+GameplayTagList=(Tag="Monster.Type.Normal",DevComment="일반 몬스터")
+GameplayTagList=(Tag="Player.Stats.Stamina",DevComment="")
+GameplayTagList=(Tag="State.Attack.End",DevComment="")
+GameplayTagList=(Tag="State.Crouch.End",DevComment="")
+GameplayTagList=(Tag="State.Player.Death",DevComment="")
+GameplayTagList=(Tag="State.Player.IsAttacking",DevComment="")
+GameplayTagList=(Tag="State.Player.IsCrouching",DevComment="")
+GameplayTagList=(Tag="State.Player.IsJumping",DevComment="")
+GameplayTagList=(Tag="State.Player.IsProning",DevComment="")
+GameplayTagList=(Tag="State.Player.IsReloading",DevComment="")
+GameplayTagList=(Tag="State.Player.IsRolling",DevComment="")
+GameplayTagList=(Tag="State.Player.IsSAing",DevComment="")
+GameplayTagList=(Tag="State.Player.IsSprinting",DevComment="")
+GameplayTagList=(Tag="State.Player.IsZooming",DevComment="")
+GameplayTagList=(Tag="State.Prone.End",DevComment="")
+GameplayTagList=(Tag="State.Roll.End",DevComment="")
+GameplayTagList=(Tag="Weapon.Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Weapon.State.Empty",DevComment="")
+GameplayTagList=(Tag="Weapon.State.Empty",DevComment="총 탄알 없음")
+GameplayTagList=(Tag="Weapon.State.Fire",DevComment="")
+GameplayTagList=(Tag="Weapon.State.Firing",DevComment="총 발사중")
+GameplayTagList=(Tag="Weapon.State.Reload",DevComment="")
+GameplayTagList=(Tag="Weapon.State.Reloading",DevComment="총 재장전 중")
+GameplayTagList=(Tag="Weapon.Type.Grenade",DevComment="무기타입-유탄발사기")
+GameplayTagList=(Tag="Weapon.Type.Grenade",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Pistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Pistol",DevComment="무기타입-권총 ")
+GameplayTagList=(Tag="Weapon.Type.Rifle",DevComment="무기타입 - 소총 태그")
+GameplayTagList=(Tag="Weapon.Type.Rifle",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Shotgun",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Shotgun",DevComment="무기타입-샷건")
+GameplayTagList=(Tag="Weapon.Type.Sniper",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Sniper",DevComment="무기타입-저격총")

